# Generated by Django 3.1.12 on 2021-12-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_auto_20211213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='administrative_unit',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
