# Generated by Django 3.1.12 on 2021-12-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_district_administrative_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='entry_permit',
            field=models.BooleanField(default=False),
        ),
    ]
