# Generated by Django 3.1.12 on 2021-12-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0004_ward_entry_permit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name_of_employee', models.CharField(max_length=256)),
                ('entry_permit', models.BooleanField(default=False)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wards.ward')),
            ],
        ),
    ]
