# Generated by Django 3.1.12 on 2021-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
