# Generated by Django 3.1.12 on 2021-12-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_ward_administrative_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='entry_permit',
            field=models.BooleanField(default=False),
        ),
    ]
