# Generated by Django 3.1.12 on 2021-12-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20211213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='entry_permit',
            field=models.BooleanField(default=False),
        ),
    ]
