# Generated by Django 3.1.12 on 2021-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20211213_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
