# Generated by Django 3.1.12 on 2021-12-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_of_department', models.CharField(max_length=256)),
            ],
        ),
    ]
